// SPDX-License-Identifier: MIT
/**
 * Generate valid GNU89 C from a seed, for fuzzing psyq-asm against the real
 * assembler (scripts/fuzz-aspsx.mjs). Deterministic: the same seed and function
 * count always yield the same text.
 *
 *   node scripts/gen-corpus.mjs <seed> [functions]
 *
 * The programs mix globals of every size class (static and extern included), a
 * table, char/short/unsigned casts, the arithmetic, shift, comparison, and
 * logical operators, conditionals, loops, switches, and calls, so the compiler
 * emits the loads, multiplies, divides, branches, and small-data accesses the
 * assembler's rules are about. They are never run.
 */

/** @param {number} seed */
function mulberry32(seed) {
  let t = seed >>> 0;
  return () => {
    t = (t + 0x6d2b79f5) >>> 0;
    let x = t;
    x = Math.imul(x ^ (x >>> 15), x | 1);
    x ^= x + Math.imul(x ^ (x >>> 7), x | 61);
    return ((x ^ (x >>> 14)) >>> 0) / 4294967296;
  };
}

const CONSTANTS = [
  0, 1, -1, 3, 7, 12, 255, 0x7fff, -0x8000, 0x8000, 0xffff, 0x10000, -123456, 0x12345678,
];
const TYPES = ['int', 'short', 'char', 'unsigned int', 'unsigned short', 'unsigned char'];
const CASTS = ['(char)', '(short)', '(unsigned char)', '(unsigned short)', '(unsigned)'];
const OPERATORS = ['+', '-', '*', '/', '%', '<<', '>>', '&', '|', '^', '<', '==', '!=', '&&', '||'];

/**
 * @param {number} seed
 * @param {number} [functions]
 * @returns {string} a C translation unit
 */
export function generate(seed, functions = 4) {
  const random = mulberry32(seed);
  const below = (n) => Math.floor(random() * n);
  const pick = (list) => list[below(list.length)];
  const constant = () => {
    const n = pick(CONSTANTS);
    return n < 0 ? `(${String(n)})` : String(n);
  };

  const lines = [`/* Generated by scripts/gen-corpus.mjs from seed ${String(seed)}. */`];
  const globals = [];
  const globalCount = 1 + below(4);
  for (let i = 0; i < globalCount; i++) {
    const storage = below(3) === 0 ? 'static ' : '';
    const init = below(2) === 0 ? ` = ${constant()}` : '';
    lines.push(`${storage}${pick(TYPES)} g${String(i)}${init};`);
    globals.push(`g${String(i)}`);
  }
  lines.push('int table[16];', 'extern int ext_value;', 'extern int ext_call(int, int);', '');

  const vars = ['a', 'b', 'c', 'x', 'y', ...globals, 'ext_value'];
  const expr = (depth) => {
    if (depth <= 0 || below(10) < 3) {
      const leaf = below(4);
      if (leaf === 0) return constant();
      if (leaf === 1) return `table[${pick(vars)} & 15]`;
      return pick(vars);
    }
    const shape = below(8);
    if (shape === 0) return `(${pick(CASTS)}${expr(depth - 1)})`;
    if (shape === 1) return `(-${expr(depth - 1)})`;
    if (shape === 2) return `(${expr(depth - 1)} ? ${expr(depth - 1)} : ${expr(depth - 1)})`;
    const op = pick(OPERATORS);
    const left = expr(depth - 1);
    let right = expr(depth - 1);
    if (op === '/' || op === '%') right = `(${right} | 1)`;
    if (op === '<<' || op === '>>') right = `(${right} & 31)`;
    return `(${left} ${op} ${right})`;
  };
  const statement = (depth, index) => {
    switch (below(8)) {
      case 3:
        return `${pick(globals)} = ${expr(2)};`;
      case 4:
        return `table[${expr(1)} & 15] = ${expr(2)};`;
      case 5:
        return depth > 0
          ? `if (${expr(2)}) { ${statement(depth - 1, index)} } else { ${statement(depth - 1, index)} }`
          : `x += ${expr(1)};`;
      case 6:
        return depth > 0
          ? `for (i = 0; i < ${String(1 + below(8))}; i++) { ${statement(depth - 1, index)} }`
          : `y ^= ${expr(1)};`;
      case 7: {
        const call = index > 0 ? `f${String(below(index))}(x, y, c)` : 'ext_call(x, y)';
        return `switch (${expr(1)} & 7) { case 0: x = ${expr(1)}; break; case 1: case 2: y = ${expr(1)}; break; case 3: x = y; case 4: y = ${call}; break; default: break; }`;
      }
      default:
        return `${pick(['x', 'y'])} = ${expr(3)};`;
    }
  };

  for (let f = 0; f < functions; f++) {
    lines.push(`${f % 3 === 2 ? 'static ' : ''}int f${String(f)}(int a, int b, unsigned c)`, '{');
    lines.push('    int x = a, y = b, i = 0;');
    const count = 3 + below(4);
    for (let s = 0; s < count; s++) lines.push(`    ${statement(2, f)}`);
    lines.push(`    return ${expr(3)} + i;`, '}', '');
  }
  return lines.join('\n');
}

if (
  process.argv[1] !== undefined &&
  import.meta.url === (await import('node:url')).pathToFileURL(process.argv[1]).href
) {
  const seed = Number(process.argv[2]);
  const functions = process.argv[3] === undefined ? undefined : Number(process.argv[3]);
  if (
    !Number.isInteger(seed) ||
    (functions !== undefined && !(Number.isInteger(functions) && functions > 0))
  ) {
    console.error('usage: node scripts/gen-corpus.mjs <seed> [functions]');
    process.exit(2);
  }
  process.stdout.write(generate(seed, functions));
}
